// src/data/languages.ts
export const content = {
  EN: {
    heroTitle: "Paloma Guth Kronbauer",
    heroSub: "Computer Science & Mathematics @ St. Olaf College",
    about: "The Archive",
    bio: "Data Engineer and Backend Developer specialized in Linux environments, Python automation, and optimizing systems for scalability and security.",
    education: "The Academy",
    edu1Title: "B.A. in Computer Science and Mathematics",
    edu1Place: "St. Olaf College | 2022 - 2026",
    edu2Title: "Neural Networks & Deep Learning",
    edu2Place: "DIS Denmark | 2025",
    eduIB: "International Baccalaureate (IB) Diploma",
    
    // St. Olaf
    stOlafTitle: "St. Olaf College",
    stOlafPlace: "Northfield, MN | 2022 - 2026",
    tagProb: "Probability & Statistics",
    tagML: "Machine Learning",
    tagForest: "Ensemble Methods",
    tagWrangling: "Data Wrangling",
    tagTheory: "Theory of Computation",
    tagSoftware: "Software Engineering",

    // DIS Denmark
    disTitle: "DIS Denmark",
    disPlace: "Copenhagen | Study Abroad",
    tagDeep: "Deep Learning",
    tagBigData: "Big Data Infra",
    tagAI: "Artificial Intelligence",
    tagGameTheory: "Game Theory",
    tagCollab: "Cloud Collaboration",

    // IB
    ibTitle: "International Baccalaureate (IB)",
    ibPlace: "UWC Maastricht | 2020 - 2022",
    tagResearch: "Academic Research",
    tagIndep: "Independent Study",
    tagInter: "Intercultural Communication",

    activeQuests: "Active Quests",
    experience: "Adventure History",
    job1Title: "Technical Lead & Mentor",
    job1Place: "St. Olaf Tech Hub | 2022 - Present",
    job2Title: "IT Support Analyst",
    job2Place: "St. Olaf IT | 2023 - 2024",
    inventory: "Inventory & Achievements",
    lvl: "Lvl.",
    skills: "Prepared Spells",
    attributesTitle: "Core Attributes",
    attr1: "System Design (INT)",
    attr2: "Documentation (CHA)",
    attr3: "Scalability (DEX)",
    attr4: "Security & Resilience (WIS)",
    spellbookTitle: "The Path of Mastery",
    levelDisclaimer: "* Expertise measured on a scale of Level 1 to Level 10",
    flavorQuote: "“Information is the mana of the modern age; logic is the circle through which we channel it.”",
    flavorAuthor: "— The Data Paladin's Creed",
    cantripTitle: "Base Cantrips (Soft Skills)",
    lvlGroupTitle: "Level {n} Spells",
    spellBookBtn: "Full Spellbook",
    tongues: "Known Tongues",
    native: "Native",
    fluent: "Fluent",
    inter: "Intermediate",
    basic: "Basic"
  },
  PT: {
    heroTitle: "Paloma Guth Kronbauer",
    heroSub: "Ciência da Computação e Matemática @ St. Olaf College",
    about: "Arquivo",
    bio: "Engenheira de Dados e Desenvolvedora Backend especializada em ambientes Linux, automação em Python e otimização de sistemas para escalabilidade e segurança.",
    education: "Academia",
    edu1Title: "Bacharelado em Ciência da Computação e Matemática",
    edu1Place: "St. Olaf College | 2022 - 2026",
    edu2Title: "Redes Neurais e Deep Learning",
    edu2Place: "DIS Denmark | 2025",
    eduIB: "Diploma de Bacharelado Internacional (IB)",

    // St. Olaf
    stOlafTitle: "St. Olaf College",
    stOlafPlace: "Northfield, MN | 2022 - 2026",
    tagProb: "Probabilidade e Estatística",
    tagML: "Machine Learning",
    tagForest: "Métodos Ensemble",
    tagWrangling: "Tratamento de Dados",
    tagTheory: "Teoria da Computação",
    tagSoftware: "Eng. de Software",

    // DIS Denmark
    disTitle: "DIS Denmark",
    disPlace: "Copenhague | Intercâmbio",
    tagDeep: "Deep Learning",
    tagBigData: "Infra de Big Data",
    tagAI: "Inteligência Artificial",
    tagGameTheory: "Teoria dos Jogos",
    tagCollab: "Colaboração em Nuvem",

    // IB
    ibTitle: "International Baccalaureate (IB)",
    ibPlace: "UWC Maastricht | 2020 - 2022",
    tagResearch: "Pesquisa Acadêmica",
    tagIndep: "Estudo Independente",
    tagInter: "Comunicação Intercultural",

    projects: "Missões Ativas",
    activeQuests: "Missões Ativas",
    experience: "Histórico de Aventuras",
    job1Title: "Gestora e Mentora Técnica",
    job1Place: "Hub de Tecnologia St. Olaf | 2022 - Atual",
    job2Title: "Analista de Suporte de TI",
    job2Place: "Suporte de TI St. Olaf | 2023 - 2024",
    inventory: "Inventário e Conquistas",
    lvl: "Nível",
    skills: "Habilidades Preparadas",
    attributesTitle: "Atributos Principais",
    attr1: "Arquitetura de Sistemas (INT)",
    attr2: "Documentação (CHA)",
    attr3: "Escalabilidade (DEX)",
    attr4: "Segurança e Resiliência (WIS)",
    spellBookBtn: "Grimório Completo",
    tongues: "Idiomas Conhecidos",
    spellbookTitle: "A Trilha da Maestria",
    levelDisclaimer: "* Experiência medida em uma escala de Nível 1 a Nível 10",
    flavorQuote: "“A informação é o mana da era moderna; a lógica é o círculo pelo qual o canalizamos.”",
    flavorAuthor: "— O Credo do Paladino de Dados",
    cantripTitle: "Cantos Iniciais (Soft Skills)",
    lvlGroupTitle: "Magias de Nível {n}",
    native: "Nativo",
    fluent: "Fluente",
    inter: "Intermediário",
    basic: "Básico"
  }
};