// src/data/languages.ts
export const content = {
  EN: {
    heroTitle: "Paloma Guth Kronbauer",
    heroSub: "Computer Science & Mathematics @ St. Olaf College",
    about: "The Archive",
    bio: "A tinkerer at heart. I spent my time at college diving deep into Math and CS theory because I believe you have to understand how a system works before you can truly master it. I’ve always been obsessed with the 'how,' so I spend my own time opening up software, kernels, and networks just to see how they tick. I’m fascinated by automation; if I can script a task to save someone else time, I will. I’m a self-taught explorer who isn't afraid of a steep learning curve, if there’s a problem I don’t know how to fix yet, I’ll stay up as long as it takes to find the answer.",
    extraTitle: "Latest fascination:",
    extraBio: "Cybersecurity. I'm still learning the ropes, but I’m constantly following the latest news and stress-testing my own setups.",
    education: "The Academy",
    
    // St. Olaf
    stOlafTitle: "St. Olaf College",
    stOlafDegree: "BA in Computer Science & Mathematics",
    stOlafMinor: "Minor in Statistics & Data Science",
    stOlafPlace: "Northfield, MN | 2022 - 2026",
    tagProb: "Probability & Statistics",
    tagML: "Machine Learning",
    tagForest: "Ensemble Methods",
    tagWrangling: "Data Wrangling",
    tagTheory: "Theory of Computation",
    tagSoftware: "Software Engineering",

    // DIS Denmark
    disTitle: "DIS Denmark",
    disDegree: "Artificial Neural Network & Deep Learning",
    disPlace: "Copenhagen | 2025",
    tagDeep: "Deep Learning",
    tagBigData: "Big Data Infra",
    tagAI: "Artificial Intelligence",
    tagGameTheory: "Game Theory",
    tagCollab: "Cloud Collaboration",

    // IB
    ibTitle: "International Baccalaureate (IB)",
    ibPlace: "UWC Maastricht | 2020 - 2022",
    tagResearch: "Academic Research",
    tagIndep: "Independent Study",
    tagInter: "Intercultural Communication",

    experience: "Adventure History",
    // Job 1
    job1Title: "Technical Lead & Mentor ",
    job1Place: "St. Olaf College - Tech Hub | 2022 - 2026",
    job1Desc: "Lead a student team in resolving hardware and software issues for the department. Along with daily support, I worked on the migration to Debian Linux and used Python to automate our metric collection.",
    // Job 2
    job2Title: "Technical Support Specialist",
    job2Place: "St Olaf College - IT | 2023 - 2024",
    job2Desc: "Managed support tickets and helped students and staff with hardware and software problems. I also managed the campus hardware inventory and wrote technical documentation so others could solve similar issues later.",
    // TA Position 
    taTitle: "Teaching Assistant - Hardware Engineering",
    taPlace: "St. Olaf College | Fall 2024",
    taDesc: "Helped students with logic gates and assembly language. I assisted with debugging their code and lead workshops to explain how the hardware works and how to apply the concepts in practice.",
    // Tags
    tagETL: "Automated ETL",
    tagPipe: "Pipeline Optimization",
    tagDoc: "Technical Documentation",
    tagAlg: "Algorithmic Logic",
    tagDebug: "System Debugging",
    tagCost: "Costumer Assistance",
    tagWorkf: "Workflow Management",

    activeQuests: "Active Quests",
    // Stardew Quest
    stardewTitle: "Stardew Valley Data Pipeline",
    stardewDesc: "Developing a data analysis of crops from the Stardew Valley game. I built a script to scrape data from the Stardew Valley Wiki, cleaned it up, and saved it into JSON files. Currently, I'm working on analyzing the data to identify which crops are actually worth the effort and using probability to predict how they'll perform.",
    tagPython: "Python",
    tagScraping: "Web Scraping",
    tagJSON: "JSON Storage",
    tagCleaning: "Data Cleaning",
    // SQL Quest
    sqlTitle: "SQL Guild Management System",
    sqlDesc: "Developing a database from scratch using D&D-inspired data. I’m focusing on schema design, using junction tables for many-to-many relationships (characters and skills) and writing complex joins to track quest participation and resource distribution.",
    tagSchema: "Schema Design",
    tagRelational: "Relational Mapping",
    tagJoins: "Complex Joins",
    tagIntegrity: "Data Integrity",

    // Button
    seeQuestLog: "View Full Quest Log",

    inventory: "Inventory & Achievements",
    lvl: "Lvl.",
    skills: "Abilities",
    attributesTitle: "Core Attributes",
    attr1: "System Design (INT)",
    attr2: "Documentation (CHA)",
    attr3: "Scalability (DEX)",
    attr4: "Security (WIS)",

    lvlGroupTitle: "Level {n} Spells",
    spellBookBtn: "Full Spellbook",
    tongues: "Known Tongues",

    spellbookTitle: "Spellbook",
    levelDisclaimer: "A record of the skills I’ve acquired. Level 10 isn't the end; it's just where the air gets thin.",
    cantripTitle: "Core Cantrips (Soft Skills)",
    flavorQuote: "Data is just noise until you find the frequency. Once the logic is anchored and the flow is steady, the rest is just channeling the spark.",
    flavorAuthor: "Unrecorded Field Notes",
    lvlMastery: "Level {n} Masteries",
    futureQuest: "Future Quest...",
    
    // Arrays for the Skills Page
    cantrips: ["Technical Communication", "Problem Solving", "Systemic Thinking", "Adaptability"],
    technicalSkills: [
        { name: "Javascript", lvl: 1 },
        { name: "Typescript", lvl: 2 },
        { name: "Docker Basics", lvl: 2 },
        { name: "AWS Fundamentals", lvl: 3 },
        { name: "Azure", lvl: 1 },
        { name: "Power BI", lvl: 3 },
        { name: "Kubernetes", lvl: 3 },
        { name: "Linux", lvl: 4 },
        { name: "Tensorflow", lvl: 4 },
        { name: "Scikit-learn", lvl: 5 },
        { name: "ETL", lvl: 5 },
        { name: "Bash", lvl: 6 },
        { name: "Git/GitHub", lvl: 6 },
        { name: "SQL & Databases", lvl: 6 },
        { name: "C++ / C", lvl: 7 },
        { name: "Python (Backend/Data)", lvl: 7 },
        { name: "Numpy & Pandas", lvl: 7 },
        { name: "Distributed Systems", lvl: 8 },
        { name: "Data Privacy & LGPD", lvl: 8 },
        { name: "Network Security", lvl: 8 },
        { name: "Cloud Security Arch.", lvl: 9 },
        { name: "Infrastructure as Code", lvl: 9 },
        { name: "Threat Intelligence", lvl: 9 },
        { name: "Secure System Opt.", lvl: 10 },
        { name: "Vulnerability Research", lvl: 10 },
        { name: "Data Encryption", lvl: 10 },
        { name: "REST APIs", lvl: 3 },
        { name: "Unit Testing (PyTest)", lvl: 2 },
        { name: "NoSQL (MongoDB)", lvl: 2 },
        { name: "CI/CD Basics", lvl: 3 },
        { name: "Apache Airflow", lvl: 1 },
        { name: "R", lvl: 7 }
    ],

    back: "← Return to Town",
    questTitle: "Full Quest Log",
    statusCompleted: "Completed",
    analysisBtn: "Read More",
    closeBtn: "Less",
    viewRepo: "Source Code",
    readMedium: "Read on Medium",
    readPaper: "Read Analysis",
    // Project 1
    ganShort: "A collaborative DCGAN project born from an urban data expedition in Berlin and Denmark.",
    ganFull: "This project was developed abroad in Denmark with three colleagues, inspired by a visit to Berlin. After visiting startups and state-funded labs that used data to solve urban questions, we were struck by the 'data footprint' of the city itself—specifically its street art. We wanted to see if we could treat graffiti not just as art, but as a complex system of spatial data. Using a DCGAN (Generative Adversarial Network), we built a model to synthesize urban typography like 'Wildstyle' and 'Bubble.' Beyond the technical challenge of balancing the Generator and Discriminator to avoid 'Mode Collapse,' the project was an exploration of how neural networks can interpret the creative 'chaos' of a city's visual language. It was our way of answering an urban question: can an algorithm learn the soul of a mural?",
    // Project 2
    batoceraShort: "Repurposing legacy hardware through Linux kernel and network optimization.",
    batoceraFull: "This project started as a solution to a security and performance bottleneck: legacy Windows 10 machines on campus were struggling with hardware limitations. I took two of these machines, wiped them, and installed Debian to build custom arcade stations. This led me down a rabbit hole of Linux tinkering—from fighting with outdated Wi-Fi chips that weren't compatible with modern signals (solving it through manual package injections and kernel tweaks) to bypassing restrictive campus firewalls to get the systems online. I also brought this home to my own Raspberry Pi, where I’ve been optimizing Batocera. For me, it’s about the satisfaction of understanding how the hardware actually talks to the software, and finding a workaround when the standard solutions don't work.",

    goodreadsShort: "A collaborative Big Data project transforming 16,000+ human reviews into structured network insights.",
    goodreadsFull: "Developed with a colleague for a Big Data course, this project was born from our shared interest in books and a question: does the emotional tone of a review actually match its star rating? After finding existing Kaggle datasets were too small or full of missing values, we built a custom Python scraper to collect metadata and 16,000+ reviews for 4,000 titles. We processed the text using VADER sentiment analysis and found that numerical ratings often fail to capture the full nuance of user sentiment. Additionally, we modeled the data as a complex network using the Louvain algorithm, discovering that genres like 'Politics' and 'Children’s' act as essential bridges between different literary communities. The work involved intensive data cleaning and ANOVA testing, but the most interesting part was seeing how subjective human sentiments in comments are transformed into structured data and clear numerical results.",
    
    navHome: "Home",
    navQuests: "Quests",
    navSkills: "Skills",

    langPort: "Portuguese",
    langEng: "English",
    langSpan: "Spanish",
    langGer: "German",
    native: "Native",
    fluent: "Fluent",
    inter: "Intermediate",
    basic: "Basic"
  },
  PT: {
    heroTitle: "Paloma Guth Kronbauer",
    heroSub: "Ciência da Computação e Matemática @ St. Olaf College",
    about: "Arquivo",
    bio: "Curiosa por natureza. Meu tempo na faculdade me proporcionou a base necessária para entender como os sistemas funcionam antes de sair abrindo e tentando mudar as coisas. Eu sempre quis entender o como, então a Ciência da Computação acabou sendo o ambiente perfeito para mim. Estou sempre tentando mexer em algo e, se eu ainda não sei como funciona, bem... eu vou descobrir. Sou fascinada por automação. Se eu puder criar um script para automatizar algo, eu farei (mesmo que eu passe um tempo desproporcional desenvolvendo o script comparado ao tamanho da tarefa original). Sou uma exploradora autodidata que não tem medo da curva de aprendizado. Se houver um problema que eu ainda não saiba resolver, ficarei acordada o tempo que for preciso até encontrar a resposta.",
    extraTitle: "Interesses:",
    extraBio: "Cybersegurança. Apenas uma entusiasta no momento esei que tenho muito a aprender, mas sempre que posso passo um tempo estudando os pontos fracos de sistemas e me divirto no TryHackMe.",
    education: "Academia",

    // St. Olaf
    stOlafTitle: "St. Olaf College",
    stOlafDegree: "Bacharelado em Ciência da Computação e Matemática",
    stOlafMinor: "Ênfase em Estatística e Ciência de Dados",
    stOlafPlace: "Northfield, MN | 2022 - 2026",
    tagProb: "Probabilidade e Estatística",
    tagML: "Machine Learning",
    tagForest: "Métodos Ensemble",
    tagWrangling: "Tratamento de Dados",
    tagTheory: "Teoria da Computação",
    tagSoftware: "Eng. de Software",

    // DIS Denmark
    disTitle: "DIS Denmark",
    disDegree: "Redes Neurais Artificiais e Deep Learning",
    disPlace: "Copenhague | 2025",
    tagDeep: "Deep Learning",
    tagBigData: "Infra de Big Data",
    tagAI: "Inteligência Artificial",
    tagGameTheory: "Teoria dos Jogos",
    tagCollab: "Colaboração em Nuvem",

    // IB
    ibTitle: "International Baccalaureate (IB)",
    ibPlace: "UWC Maastricht | 2020 - 2022",
    tagResearch: "Pesquisa Acadêmica",
    tagIndep: "Estudo Independente",
    tagInter: "Comunicação Intercultural",

    experience: "Histórico de Aventuras",
    // Job 1
    job1Title: "Gestora e Mentora Técnica",
    job1Place: "St. Olaf College - Tech Hub | 2022 - 2026",
    job1Desc: "Liderei uma equipe de estudantes na resolução de problemas de hardware e software. Além do suporte, trabalhei na migração para Debian Linux e usei Python para automatizar a coleta de métricas.",    
    
    //Job 2
    job2Title: "Especialista em Suporte Técnico",
    job2Place: "St. Olaf College - TI | 2023 - 2024",
    job2Desc: "Trabalhei com chamados (tickets) e ajudei alunos e funcionários com problemas de hardware e software. Também cuidei do inventário e escrevi documentação técnica para que outros pudessem resolver problemas parecidos no futuro.",
    // TA Position 
    taTitle: "Monitora - Engenharia de Hardware",
    taPlace: "St. Olaf College | Segundo semestre 2024",
    taDesc: "Ajudei alunos com portas lógicas e linguagem assembly. Auxiliei na depuração de códigos e realizo workshops para explicar o funcionamento do hardware e como aplicar os conceitos na prática.",

    tagETL: "ETL Automatizado",
    tagPipe: "Otimização de Pipeline",
    tagDoc: "Documentação Técnica",
    tagAlg: "Lógica Algorítmica",
    tagDebug: "Depuração de Sistemas",
    tagCost: "Atendimento ao Cliente",
    tagWorkf: "Gestão de Fluxo",

    activeQuests: "Missões Ativas",
    // Stardew Quest
    stardewTitle: "Pipeline de Dados Stardew Valley",
    stardewDesc: "Desenvolvendo uma análise dos dados de plantações e produtos no jogo Stardew Valley. Criei um script para extrair dados da Wiki de Stardew Valley, limpei tudo e salvei em arquivos JSON. Com o projeto em andamento, estou analisando os dados para saber quais plantações realmente valem o tempo gasto em jogo.",
    tagPython: "Python",
    tagScraping: "Web Scraping",
    tagJSON: "Armazenamento JSON",
    tagCleaning: "Limpeza de Dados",
    // SQL Quest
    sqlTitle: "Sistema de Gestão de Guildas (SQL)",
    sqlDesc: "Projeto ainda nos primórdios, desenvolvido do zero com dados inspirados em Dungeons & Dragons. Objetivo do projeto é estruturar relacionamentos muitos-para-muitos entre personagens e habilidades através de tabelas intermediárias e implementando joins para o rastreamento de participação em missões.",
    tagRelational: "Mapeamento Relacional",
    tagJoins: "Joins Complexos",
    tagIntegrity: "Integridade de Dados",
    // Button
    seeQuestLog: "Ver Diário de Missões",

    inventory: "Inventário e Conquistas",
    lvl: "Nível",
    skills: "Habilidades",
    attributesTitle: "Atributos Principais",
    attr1: "Arquitetura de Sistemas (INT)",
    attr2: "Documentação (CHA)",
    attr3: "Escalabilidade (DEX)",
    attr4: "Segurança (WIS)",
    spellBookBtn: "Grimório Completo",
    tongues: "Idiomas Conhecidos",
  
    lvlGroupTitle: "Magias de Nível {n}",

    spellbookTitle: "Grimório",
    levelDisclaimer: "Um registro das habilidades que adquiri. O nível 10 não é o fim; é apenas onde o ar começa a rarear.",    
    cantripTitle: "Cantrips Essenciais (Soft Skills)",
    flavorQuote: "Dados são apenas ruído até você encontrar a frequência. Quando a lógica está ancorada e o fluxo estável, o que resta é apenas canalizar a faísca.",    
    flavorAuthor: "Notas de Campo não Registradas",
    lvlMastery: "Habilidades de Nível {n}",
    futureQuest: "Missão Futura...",

    cantrips: ["Comunicação Técnica", "Resolução de Problemas", "Pensamento Sistêmico", "Adaptabilidade"],
    technicalSkills: [
      { name: "Javascript", lvl: 1 },
      { name: "Typescript", lvl: 2 },
      { name: "Docker (Básico)", lvl: 2 },
      { name: "AWS Fundamentos", lvl: 3 },
      { name: "Azure", lvl: 1 },
      { name: "Power BI", lvl: 3 },
      { name: "Kubernetes", lvl: 3 },
      { name: "Linux", lvl: 4 },
      { name: "Tensorflow", lvl: 4 },
      { name: "Scikit-learn", lvl: 5 },
      { name: "ETL (Extração e Limpeza)", lvl: 5 },
      { name: "Bash", lvl: 6 },
      { name: "Git / GitHub", lvl: 6 },
      { name: "SQL & Bancos de Dados", lvl: 6 },
      { name: "C++ / C", lvl: 7 },
      { name: "Python (Backend/Dados)", lvl: 7 },
      { name: "Numpy & Pandas", lvl: 7 },
      { name: "Sistemas Distribuídos", lvl: 8 },
      { name: "Privacidade de Dados & LGPD", lvl: 8 },
      { name: "Segurança de Redes", lvl: 8 },
      { name: "Arquitetura de Nuvem Segura", lvl: 9 },
      { name: "Infraestrutura como Código (IaC)", lvl: 9 },
      { name: "Inteligência de Ameaças", lvl: 9 },
      { name: "Otimização de Sistemas Seguros", lvl: 10 },
      { name: "Pesquisa de Vulnerabilidades", lvl: 10 },
      { name: "Criptografia de Dados", lvl: 10 },
      { name: "APIs REST", lvl: 3 },
      { name: "Testes Unitários (PyTest)", lvl: 2},
      { name: "NoSQL (MongoDB)", lvl: 2 },
      { name: "CI/CD (Fundamentos)", lvl: 3 },
      { name: "Apache Airflow", lvl: 1 },
      { name: "R", lvl: 7 }
    ],

    back: "← Voltar para a Vila",
    questTitle: "Diário de Missões Completo",
    statusCompleted: "Concluído",
    analysisBtn: "Ler Mais",
    closeBtn: "Menos",
    viewRepo: "Código Fonte",
    readPaper: "Ler Análise",
    readMedium: "Ler no Medium",
    // Project 1
    ganShort: "Um projeto colaborativo de DCGAN nascido de uma expedição de dados urbanos em Berlim e Dinamarca.",
    ganFull: "Projeto desenvolvido durante um intercâmbio na Dinamarca com três colegas, inspirado por uma visita a Berlim. Após visitarmos startups e laboratórios estatais que utilizavam análise de dados para resolver questões urbanas, nos interessamos por como a cidade hub para todos os tipos de dados, visuais e numéricos, especificamente sua arte de rua. Nosso foco for em testar se o graffiti poderia ser tratado não apenas como arte, mas como um sistema complexo de dados espaciais. Utilizando uma DCGAN (Rede Adversária Generativa), construímos um modelo para sintetizar tipografias urbanas como 'Wildstyle' e 'Bubble'. Além do desafio técnico de equilibrar o Gerador e o Discriminador para evitar o 'Mode Collapse', o projeto foi uma exploração de como as redes neurais podem interpretar o 'caos' criativo da linguagem visual de uma metrópole. Foi a nossa forma de responder a uma pergunta urbana: pode um algoritmo aprender a alma de um mural?",
    // Project 2
    batoceraShort: "Recuperação de hardware legado através de otimização de kernel Linux e redes.",
    batoceraFull: "Este projeto surgiu como uma solução prática para um gargalo de segurança e desempenho: máquinas antigas com Windows 10 no campus estavam no limite de seu hardware. Recuperei duas dessas estações, migrando-as para Debian para criar arcades personalizados. Esse projeto me levou a querer aprender mais sobre o ecossistema Linux, desde solucionar problemas com chips Wi-Fi obsoletos (resolvido via injeção manual de pacotes e ajustes de kernel) até lidar com as restrições de firewall do campus. Trouxe esse aprendizado para o meu próprio Raspberry Pi com Batocera, onde sigo otimizando o sistema. Para mim, o mais interessante é entender como o hardware se comunica com o software, buscando alternativas quando as soluções convencionais não atendem.",

    goodreadsShort: "Projeto colaborativo de Big Data transformando mais de 16.000 resenhas humanas em insights de redes estruturadas.",
    goodreadsFull: "Desenvolvido com um colega para uma disciplina de Big Data (Dinamarca), este projeto nasceu do nosso interesse comum por livros e de uma pergunta: o tom emocional de uma resenha realmente condiz com sua nota? Ao percebermos que os datasets do Kaggle eram limitados ou cheios de valores nulos, construímos um scraper em Python para coletar metadados e mais de 16.000 avaliações de 4.000 títulos. Processamos o texto via análise de sentimento VADER e descobrimos que as notas numéricas muitas vezes não captam a nuance do sentimento do usuário. Além disso, modelamos os dados como uma rede complexa usando o algoritmo Louvain, identificando que gêneros como 'Política' e 'Infantil' atuam como pontes essenciais entre diferentes comunidades literárias. O trabalho envolveu limpeza de dados e testes ANOVA, mas o ponto mais interessante foi observar como sentimentos humanos subjetivos expressos em comentários são transformados em dados estruturados e resultados numéricos.",
    
    navHome: "Início",
    navQuests: "Missões",
    navSkills: "Habilidades",

    langPort: "Português",
    langEng: "Inglês",
    langSpan: "Espanhol",
    langGer: "Alemão",
    native: "Nativo",
    fluent: "Fluente",
    inter: "Intermediário",
    basic: "Básico",
  }
};